In [1]:
import pandas as pd

df = pd.read_excel(r'H:\work\zaki\automation\data\raw_data.xlsx')
df.head()

,الاسم و لقب,رقم الهاتف,الولاية,العنوان,comment-3,produits,السعر,status,EXPEDITION,comment-1,comment-2
0,ALIAMMAR,0662 16 21 29,tiaret,tiaret,56,قشابية,8500DA,confirmer,expidie,gris foncé,bureau
1,حسان وحيد,661237466,Blida,Blida,XXXXL,قشابية,8500DA,confirmer,expidie,maron foncé,bureau
2,قطاف,771517160,البليدة,بلدية مفتاح,1900-03-02 00:00:00,قشابية,8500DA,confirmer,expidie,maron foncé,bureau
3,Amine BENAOUDA,557386956,Relizane,Plateau remonte n 7 Relizane,58,قشابية,8500DA,confirmer,expidie,gris clair,للمنزل
4,علي,771576542,سدي بلعباس,16شارع لعوج قاضي,Large,قشابية,8500DA,confirmer,expidie,maron,للمنزل

In [2]:
df = df.drop(columns = ['status','EXPEDITION'])
df = df[['الاسم و لقب','رقم الهاتف','الولاية','العنوان','produits','السعر','comment-3','comment-1','comment-2']]
df.head()

,الاسم و لقب,رقم الهاتف,الولاية,العنوان,produits,السعر,comment-3,comment-1,comment-2
0,ALIAMMAR,0662 16 21 29,tiaret,tiaret,قشابية,8500DA,56,gris foncé,bureau
1,حسان وحيد,661237466,Blida,Blida,قشابية,8500DA,XXXXL,maron foncé,bureau
2,قطاف,771517160,البليدة,بلدية مفتاح,قشابية,8500DA,1900-03-02 00:00:00,maron foncé,bureau
3,Amine BENAOUDA,557386956,Relizane,Plateau remonte n 7 Relizane,قشابية,8500DA,58,gris clair,للمنزل
4,علي,771576542,سدي بلعباس,16شارع لعوج قاضي,قشابية,8500DA,Large,maron,للمنزل

In [3]:
df['reference'] = df['produits']
df.insert(0, 'reference', df.pop('reference'))
df[['comment-1','comment-2','comment-3']] = df[['comment-1','comment-2','comment-3']].astype(str)
df['remarque'] = df['comment-3'] + '+' + df['comment-1'] + '+' + df['comment-2']
df = df.drop(columns = ['comment-3','comment-1','comment-2'])
df.head()

,reference,الاسم و لقب,رقم الهاتف,الولاية,العنوان,produits,السعر,remarque
0,قشابية,ALIAMMAR,0662 16 21 29,tiaret,tiaret,قشابية,8500DA,56+gris foncé+bureau
1,قشابية,حسان وحيد,661237466,Blida,Blida,قشابية,8500DA,XXXXL+maron foncé+bureau
2,قشابية,قطاف,771517160,البليدة,بلدية مفتاح,قشابية,8500DA,1900-03-02 00:00:00+maron foncé+bureau
3,قشابية,Amine BENAOUDA,557386956,Relizane,Plateau remonte n 7 Relizane,قشابية,8500DA,58+gris clair+للمنزل
4,قشابية,علي,771576542,سدي بلعباس,16شارع لعوج قاضي,قشابية,8500DA,Large+maron+للمنزل

In [4]:
df.rename(columns = {'الاسم و لقب':'nom et prenom du destinataire*','رقم الهاتف':'telephone*','الولاية':'wilaya de livraison','العنوان':'adresse de livraison*','produits':'produit (référence)*','السعر':'montant du colis*'}, inplace = True)
df['nom et prenom du destinataire*'].fillna('pas de nom', inplace = True)
df.head()

C:\Users\mouncef\AppData\Local\Temp\ipykernel_8792\2033075164.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['nom et prenom du destinataire*'].fillna('pas de nom', inplace = True)

,reference,nom et prenom du destinataire*,telephone*,wilaya de livraison,adresse de livraison*,produit (référence)*,montant du colis*,remarque
0,قشابية,ALIAMMAR,0662 16 21 29,tiaret,tiaret,قشابية,8500DA,56+gris foncé+bureau
1,قشابية,حسان وحيد,661237466,Blida,Blida,قشابية,8500DA,XXXXL+maron foncé+bureau
2,قشابية,قطاف,771517160,البليدة,بلدية مفتاح,قشابية,8500DA,1900-03-02 00:00:00+maron foncé+bureau
3,قشابية,Amine BENAOUDA,557386956,Relizane,Plateau remonte n 7 Relizane,قشابية,8500DA,58+gris clair+للمنزل
4,قشابية,علي,771576542,سدي بلعباس,16شارع لعوج قاضي,قشابية,8500DA,Large+maron+للمنزل

In [5]:
df['telephone 2'] = None
df['code wilaya*'] = None
df['commune de livraison*'] = None
df['poids (kg)'] = None
df['FRAGILE'] = None
df['OUVRIR'] = None
df['ECHANGE'] = None
df['STOP DESK'] = None
df['Lien map'] = None
df = df[['reference','nom et prenom du destinataire*','telephone*','telephone 2','code wilaya*','wilaya de livraison','commune de livraison*','adresse de livraison*','produit (référence)*','poids (kg)','montant du colis*','remarque','FRAGILE','OUVRIR','ECHANGE','STOP DESK','Lien map']]

df.head()

,reference,nom et prenom du destinataire*,telephone*,telephone 2,code wilaya*,wilaya de livraison,commune de livraison*,adresse de livraison*,produit (référence)*,poids (kg),montant du colis*,remarque,FRAGILE,OUVRIR,ECHANGE,STOP DESK,Lien map
0,قشابية,ALIAMMAR,0662 16 21 29,None,None,tiaret,None,tiaret,قشابية,None,8500DA,56+gris foncé+bureau,None,None,None,None,None
1,قشابية,حسان وحيد,661237466,None,None,Blida,None,Blida,قشابية,None,8500DA,XXXXL+maron foncé+bureau,None,None,None,None,None
2,قشابية,قطاف,771517160,None,None,البليدة,None,بلدية مفتاح,قشابية,None,8500DA,1900-03-02 00:00:00+maron foncé+bureau,None,None,None,None,None
3,قشابية,Amine BENAOUDA,557386956,None,None,Relizane,None,Plateau remonte n 7 Relizane,قشابية,None,8500DA,58+gris clair+للمنزل,None,None,None,None,None
4,قشابية,علي,771576542,None,None,سدي بلعباس,None,16شارع لعوج قاضي,قشابية,None,8500DA,Large+maron+للمنزل,None,None,None,None,None

In [6]:
df['telephone*'] = df['telephone*'].astype(str)
df['telephone*'] = df['telephone*'].str.replace(' ', '')
df['telephone*'] = '0'+df['telephone*']
df.head()

,reference,nom et prenom du destinataire*,telephone*,telephone 2,code wilaya*,wilaya de livraison,commune de livraison*,adresse de livraison*,produit (référence)*,poids (kg),montant du colis*,remarque,FRAGILE,OUVRIR,ECHANGE,STOP DESK,Lien map
0,قشابية,ALIAMMAR,00662162129,None,None,tiaret,None,tiaret,قشابية,None,8500DA,56+gris foncé+bureau,None,None,None,None,None
1,قشابية,حسان وحيد,0661237466,None,None,Blida,None,Blida,قشابية,None,8500DA,XXXXL+maron foncé+bureau,None,None,None,None,None
2,قشابية,قطاف,0771517160,None,None,البليدة,None,بلدية مفتاح,قشابية,None,8500DA,1900-03-02 00:00:00+maron foncé+bureau,None,None,None,None,None
3,قشابية,Amine BENAOUDA,0557386956,None,None,Relizane,None,Plateau remonte n 7 Relizane,قشابية,None,8500DA,58+gris clair+للمنزل,None,None,None,None,None
4,قشابية,علي,0771576542,None,None,سدي بلعباس,None,16شارع لعوج قاضي,قشابية,None,8500DA,Large+maron+للمنزل,None,None,None,None,None

In [82]:
commune_data = pd.read_excel(r'H:\work\zaki\automation\data\process_data.xlsx',sheet_name='communes')
pro_df = pd.read_excel(r'H:\work\zaki\automation\data\process_data.xlsx')
pro_df.head()

,date,reference commande,nom et prenom du destinataire*,telephone*,telephone 2,code wilaya*,wilaya de livraison,commune de livraison*,adresse de livraison*,produit (référence)*,poids (kg),montant du colis*,remarque,FRAGILE,OUVRIR,ECHANGE,STOP DESK,Lien map
0,2023-11-06,HS1,Akram RiGiy,0662137570,NaN,19.0,Sétif,El Eulma,العلمة,مرهم,NaN,3000.0,NaN,NaN,NaN,NaN,--,NaN
1,2023-11-06,HS2,عبد الرزاق دبيزات,0665749462,NaN,30.0,Ouargla,Ouargla,الشرفة,مرهم,NaN,3200.0,NaN,NaN,NaN,NaN,--,NaN
2,2023-11-06,HS3,Ben Aissa Redouane,0561662362,NaN,16.0,Alger,Alger Centre,Alger,مرهم,NaN,2800.0,NaN,NaN,NaN,NaN,--,NaN
3,2023-11-06,HS4,درقام مسعود,0771545148,NaN,10.0,Bouira,Bouira,البويرة,مرهم,NaN,3000.0,NaN,NaN,NaN,NaN,--,NaN
4,2023-11-06,HS5,MOHAMED26566616,0665150882,NaN,31.0,Oran,Ain Turk,ain turk troville,مرهم,NaN,3000.0,NaN,NaN,NaN,NaN,--,NaN

In [83]:
import google.generativeai as genai
import pandas as pd
import re
import time

# Set your API key
genai.configure(api_key="AIzaSyCggDnTG__jpKsRNaMiclJDEGucy4PqobA")

# Initialize Gemini model
model = genai.GenerativeModel('gemini-2.0-flash')

# Load predefined commune names from another sheet
commune_names = commune_data['nom communes'].tolist()  # Assuming 'nom commune' is the column name

# Function to query Gemini for 'code wilaya' and 'nom commune'
def get_wilaya_info(wilaya_name, address, commune_names):
    prompt = f'''For the wilaya: {wilaya_name} in Algeria and address: {address}, provide the 'code wilaya' and 'nom commune'.
    The 'nom commune' must be one of the following: {", ".join(commune_names)}.
    Use the following format:
    "code wilaya": "XX",
    "nom commune": "XXXXX"
    Ensure the response contains only the code wilaya as a two-digit number and the nom commune as a string from the provided list.'''
    response = model.generate_content(prompt)
    return response.text

# Function to extract the code wilaya and nom commune from the response
def extract_info(response_text):
    code_wilaya_match = re.search(r'"code wilaya":\s*"(\d{2})"', response_text)
    nom_commune_match = re.search(r'"nom commune":\s*"([^"]+)"', response_text)
    
    code_wilaya = code_wilaya_match.group(1) if code_wilaya_match else None
    nom_commune = nom_commune_match.group(1) if nom_commune_match else None
    
    return code_wilaya, nom_commune

# Example usage
wilaya_info = {}
cooldown_time = 5  # Cooldown period in seconds

for index, row in df.iterrows():
    wilaya = row['wilaya de livraison']
    address = row['adresse de livraison*']
    try:
        # Get the response from Gemini
        response_text = get_wilaya_info(wilaya, address, commune_names)
        
        # Extract the code wilaya and nom commune from the response
        code_wilaya, nom_commune = extract_info(response_text)
        
        # Add the result to wilaya_info
        wilaya_info[wilaya] = {
            "code wilaya": code_wilaya,
            "nom commune": nom_commune,
            "wilaya de livraison": wilaya,
            "adresse de livraison*": address
        }
        
        # Print progress
        print(f"Processed {wilaya}: code wilaya={code_wilaya}, nom commune={nom_commune}")
        
        # Add a cooldown period between requests
        time.sleep(cooldown_time)
    except Exception as e:
        print(f"Error processing {wilaya}: {e}")
        wilaya_info[wilaya] = {
            "code wilaya": None,
            "nom commune": None,
            "wilaya de livraison": wilaya,
            "adresse de livraison*": address
        }

print("Wilaya Info:", wilaya_info)

Processed باتنة نڨاوس: code wilaya=05, nom commune=N Gaous
Processed Alger: code wilaya=16, nom commune=Souidania
Processed عين الدفلة: code wilaya=44, nom commune=Khemis Miliana
Processed تبسة: code wilaya=12, nom commune=Boukhadra
Processed Ain témouchent: code wilaya=46, nom commune=Beni Saf
Processed تبسة: code wilaya=12, nom commune=El Houidjbet
Processed تبسة: code wilaya=12, nom commune=Lmirige
Processed مستغانم: code wilaya=27, nom commune=Achaacha
Processed برج بوعريريج: code wilaya=34, nom commune=El M'hir
Processed سطيف: code wilaya=19, nom commune=Setif
Processed alger: code wilaya=16, nom commune=Alger Centre
Processed elharach: code wilaya=16, nom commune=El Harrach
Processed الاخضرية: code wilaya=10, nom commune=Lakhdaria
Processed المدية: code wilaya=26, nom commune=Medea
Processed ouargla: code wilaya=30, nom commune=Ouargla
Processed Boumerdes: code wilaya=35, nom commune=Isser
Processed الجلفة: code wilaya=17, nom commune=Ain Oussera
Wilaya Info: {'باتنة نڨاوس': {'code wilaya': '05', 'nom commune': 'N Gaous', 'wilaya de livraison': 'باتنة نڨاوس', 'adresse de livraison*': 'راس العين'}, 'Alger': {'code wilaya': '16', 'nom commune': 'Souidania', 'wilaya de livraison': 'Alger', 'adresse de livraison*': 'Sites 5 juillet suidania'}, 'عين الدفلة': {'code wilaya': '44', 'nom commune': 'Khemis Miliana', 'wilaya de livraison': 'عين الدفلة', 'adresse de livraison*': 'خميس مليانه'}, 'تبسة': {'code wilaya': '12', 'nom commune': 'Lmirige', 'wilaya de livraison': 'تبسة', 'adresse de livraison*': 'الكلتوس مشتة بلدية لمريج'}, 'Ain témouchent': {'code wilaya': '46', 'nom commune': 'Beni Saf', 'wilaya de livraison': 'Ain témouchent', 'adresse de livraison*': '225 La zhun Béni saf'}, 'مستغانم': {'code wilaya': '27', 'nom commune': 'Achaacha', 'wilaya de livraison': 'مستغانم', 'adresse de livraison*': 'عشعاشة'}, 'برج بوعريريج': {'code wilaya': '34', 'nom commune': "El M'hir", 'wilaya de livraison': 'برج بوعريريج', 'adresse de livraison*': 'السلاطنه بلديه المهير'}, 'سطيف': {'code wilaya': '19', 'nom commune': 'Setif', 'wilaya de livraison': 'سطيف', 'adresse de livraison*': 'حي عين طريق سطيف'}, 'alger': {'code wilaya': '16', 'nom commune': 'Alger Centre', 'wilaya de livraison': 'alger', 'adresse de livraison*': 'alger'}, 'elharach': {'code wilaya': '16', 'nom commune': 'El Harrach', 'wilaya de livraison': 'elharach', 'adresse de livraison*': 'algir'}, 'الاخضرية': {'code wilaya': '10', 'nom commune': 'Lakhdaria', 'wilaya de livraison': 'الاخضرية', 'adresse de livraison*': 'البويرة'}, 'المدية': {'code wilaya': '26', 'nom commune': 'Medea', 'wilaya de livraison': 'المدية', 'adresse de livraison*': 'المدية حي المصلى'}, 'ouargla': {'code wilaya': '30', 'nom commune': 'Ouargla', 'wilaya de livraison': 'ouargla', 'adresse de livraison*': 'عين البيضاء'}, 'Boumerdes': {'code wilaya': '35', 'nom commune': 'Isser', 'wilaya de livraison': 'Boumerdes', 'adresse de livraison*': 'isser'}, 'الجلفة': {'code wilaya': '17', 'nom commune': 'Ain Oussera', 'wilaya de livraison': 'الجلفة', 'adresse de livraison*': 'عين وسارة'}}

In [84]:
df['code wilaya*'] = df['wilaya de livraison'].map(lambda x: wilaya_info[x]['code wilaya'])
df['commune de livraison*'] = df['wilaya de livraison'].map(lambda x: wilaya_info[x]['nom commune'])
df.head()

,reference,nom et prenom du destinataire*,telephone*,telephone 2,code wilaya*,wilaya de livraison,commune de livraison*,adresse de livraison*,produit (référence)*,poids (kg),montant du colis*,remarque,FRAGILE,OUVRIR,ECHANGE,STOP DESK,Lien map
0,ROBE SALI,شحال توصيل,0663744330,None,05,باتنة نڨاوس,N Gaous,راس العين,ROBE SALI,None,3900,9سنوات+حمرا +للمنزل,None,None,None,None,None
1,ROBE SALI,bleu 8ans,0795599968,None,16,Alger,Souidania,Sites 5 juillet suidania,ROBE SALI,None,3900,8 ans+زرقاء +للمنزل,None,None,None,None,None
2,ROBE SALI,ابراهيم,0777793049,None,44,عين الدفلة,Khemis Miliana,خميس مليانه,ROBE SALI,None,3900,2025-08-12 00:00:00+حمرا+للمنزل,None,None,None,None,None
3,ROBE SALI,محمد,0777877124,None,12,تبسة,Lmirige,بلدية بوخضرة,ROBE SALI,None,3900,10 سنوات+احمر+للمنزل,None,None,None,None,None
4,ROBE SALI,Attari kader,0775496352,None,46,Ain témouchent,Beni Saf,225 La zhun Béni saf,ROBE SALI,None,3900,8 ans+زرقاء+للمنزل,None,None,None,None,None

In [85]:
df.to_csv(r'H:\work\zaki\automation\upload\upload.csv', index=False)